// <auto-generated />
using BarcodeGenerator.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BarcodeGenerator.Persistence.Migrations
{
    [DbContext(typeof(BarcodeGeneratorDbContext))]
    [Migration("20240926070753_CreateViewInventoryVoucher")]
    partial class CreateViewInventoryVoucher
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BarcodeGenerator.Domain.Entities.InventoryVoucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CounterpartDLCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("VoucherNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PartName", "VoucherNumber")
                        .IsUnique();

                    b.ToTable("InventoryVoucher", (string)null);
                });

            modelBuilder.Entity("BarcodeGenerator.Domain.Entities.InventoryVoucherSerialNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InventoryVoucherId")
                        .HasColumnType("int");

                    b.Property<int>("PrintCounter")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("InventoryVoucherId");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("InventoryVoucherSerialNumber", (string)null);
                });

            modelBuilder.Entity("BarcodeGenerator.Domain.Entities.InventoryVoucherSerialNumber", b =>
                {
                    b.HasOne("BarcodeGenerator.Domain.Entities.InventoryVoucher", "InventoryVoucher")
                        .WithMany("SerialNumbers")
                        .HasForeignKey("InventoryVoucherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryVoucher");
                });

            modelBuilder.Entity("BarcodeGenerator.Domain.Entities.InventoryVoucher", b =>
                {
                    b.Navigation("SerialNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
